<?php

namespace App\ModelBundle\Repository;

/**
 * AttachRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttachRepository extends \Doctrine\ORM\EntityRepository
{
}
